name: nathancunningham.com
favicon: null
layout_spectrum: 0.41813
typography_spectrum: 0.2723404
title: "Nathan's Progress Report"
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cab57c'
    - '#b59451'
    - '#190e0e'
    - '#392d27'
  brandStrength: 0.6875
  lightness: 0.3619298024568707
  saturation: 0.7050722283311188
  rhythmicContrast: 0.3830534636508673
purpose: []
