title: "Nathan's Progress"
cta:
  version: null
  bucket: null
  domain: null
layout_spectrum: 0.49398
favicon: null
name: nathancunningham.com
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.8340213848277926
  saturation: 0.7050722283311188
  brandColors:
    - '#ffffff'
    - '#cab57c'
    - '#b59451'
    - '#190e0e'
    - '#392d27'
  lightness: 0.3619298024568707
  rhythmicContrast: 0.3830534636508673
typography_spectrum: 0.2723404
