name: nathancunningham.com
favicon: null
layout_spectrum: 0.49398
typography_spectrum: 0.5
title: To Progress
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cab57c'
    - '#b59451'
    - '#190e0e'
    - '#392d27'
  brandStrength: 0.8340213848277926
  lightness: 0.3619298024568707
  saturation: 0.7050722283311188
  rhythmicContrast: 0.38305346365086734
purpose: []
